### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by wesoos** [angelcam/arrow-client#15]
Hello, how do I get notified about new releases of the arrow-client code?  And how do I go about upgrading an existing installation?

Thanks
Wessel

**Comment by operutka** [comment]
Hi @wesoos,

you can simply "watch" the project (i.e. click on the watch button below the top black line) and you'll get notifications directly from GitHub.

I'm not sure what you mean by existing installation. If you compiled the code yourself, you'll need to git pull the changes and recompile it. If you use our DEB package, you can use APT to fetch new updates. If you have our AngelBox, it'll get updated automatically, once a new version of the client is released.

Regards,
Ondrej

**Comment by wesoos** [comment]
I wasn’t aware you had a DEB package.  I was always compiling my own.  What is the package name?

What is the git pull command to run?  And will there be any breaking changes?

Thanks

Wessel Oosthuizen

**Comment by operutka** [comment]
The DEB package is currently available for Debian Jessie based Linux distributions running on armhf platforms. Instructions for installing the client can be found here:
https://github.com/angelcam/arrow-client/wiki/Turning-your-ARM-device-into-AngelBox#installation-from-our-apt-repository

If you'd rather like to fetch changes from our GIT repository and compile the client yourself, run the following commands in the root of your source tree:
```bash
git pull origin
# replace VERSION with an actual version, e.g. v0.7.1
git checkout VERSION
# to build the client
cargo build --release
# to build the client including the network scanner
cargo build --release --features discovery
```

The project follows semantic versioning, so any breaking change is indicated by a change in the major version number or by a change in the minor version number if major is zero. There are no breaking changes in the command line interface between versions 0.6.x and 0.7.x. The minor version number changed mainly due to big changes in project dependencies and implementation.

**Comment by wesoos** [comment]
Ok thanks.  We only Ubuntu desktop devices.  Do you have plans for a package for it?

Wessel Oosthuizen

**Comment by operutka** [comment]
Currently, there are no plans for making x86 packages for Ubuntu. However, it might change in the future.

**Comment by wesoos** [comment]
If I do a re-compile of the client, would it change the UUID and mess up the AngelBox ID?

Thanks

Wessel Oosthuizen

**Comment by operutka** [comment]
Hi @wesoos,
I'm sorry for the delay. Using new version of the Arrow client will not change your UUID. Your AngelBox ID should work just fine after the update. Please note that it's recommended to backup your `/etc/arrow/config.json` before updating your client.

**Comment by operutka** [comment]
I hope that I've answered your questions, so I'm closing this issue.
