### ISSUE TITLE
Building per instructions doesn't work

### ISSUE THREAD

**Issue by troykelly** [angelcam/arrow-client#17]
Hello - building per the [instructions](https://github.com/angelcam/arrow-client/wiki/Turning-your-ARM-device-into-AngelBox) installs fine, but the log just shows the below.

I did try the SD image - but that wouldn't even boot.

So packages installed per instructions on a clean image.

Is there any actual logging anywhere?

```
May 24 03:14:46 raspberrypi root: the Arrow Client process has exited with code 127
May 24 03:14:56 raspberrypi root: the Arrow Client process has exited with code 127
May 24 03:15:06 raspberrypi root: the Arrow Client process has exited with code 127
May 24 03:15:16 raspberrypi root: the Arrow Client process has exited with code 127
May 24 03:15:26 raspberrypi root: the Arrow Client process has exited with code 127
May 24 03:15:36 raspberrypi root: the Arrow Client process has exited with code 127
May 24 03:15:46 raspberrypi root: the Arrow Client process has exited with code 127

```

**Comment by troykelly** [comment]
Looks like you are missing a library... Running manually yields
`/usr/local/arrow-box/arrow-client: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

and then...

`/usr/local/arrow-box/arrow-client: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
`

**Comment by troykelly** [comment]
A hacky [work around...](https://gist.github.com/troykelly/a273bfbe7348044ebc8df9ecd913c3fc)

**Comment by operutka** [comment]
Hi @troykelly,

you were probably trying to install the package on the latest version of Raspbian (it's Stretch if I'm correct). Our package is built for an older version of Raspbian - Raspbian Jessie. That's why you see the error with missing libraries.

Your system have those libraries but in a newer version. The Arrow client was linked against `libssl.so.1.0.0` and `libcrypto.so.1.0.0` but your system has only `libssl.so.1.0.2` and `libcrypto.so.1.0.2`. Your workaround might work but I wouldn't recommend it as it might make the Arrow client unstable. The correct solution would be using Raspbian Jessie.

Regarding our image - the `2018-02-14` version should work fine for Raspberry Pi 2 and 3. We use the same image for AngelBoxes that we sell on Amazon. Please note there are two different images - one that is named `angel-box-opi-*.img.zip`, which is built for Orange Pi and **it will not work with Raspberry Pi**, and one that is named `angel-box-rpi-*.img.zip`, which is built for Raspberry Pi 2 and 3.

**Comment by troykelly** [comment]
No, the image doesn't appear to work. `angel-box-rpi-2018-02-14.img.zip` fails to boot on a Pi 3
Not sure why you would want to use the older version when stretch has been out for a while, and unless you are doing something special - I can't see a fix for Broadpwn exploit (just as an example as to why you would not want to stick with the older base image).

**Comment by operutka** [comment]
Hi @troykelly,

I'm sorry for the delay. I had to find some time to test it myself again.

I've tested it with Raspberry Pi 3 and it simply works. I followed the instructions [here](https://github.com/angelcam/arrow-client/wiki/Turning-your-ARM-device-into-AngelBox) step by step. I downloaded the `angel-box-rpi-2018-02-14.img.zip` image and flashed it using Etcher. The device was up and running within 20 seconds once I plugged the power in. How exactly did you flash your image?

Regarding the version of Raspbian - our package was built for Raspbian Jessie and, unfortunately, it does not work with newer versions because of the OpenSSL dependency. It does not mean that we want to stick with Jessie forever. It just means that we haven't had time to build a package for Stretch and test it properly. There will definitely be a Stretch version of the package. I just cannot say when exactly it will be ready.

**Comment by operutka** [comment]
Hi @troykelly,
there is a new version of the package for Raspbian Stretch (see the updated [wiki](https://github.com/angelcam/arrow-client/wiki/Turning-your-ARM-device-into-AngelBox) page) along with a new image based on Raspbian Stretch. The old image had a problem with booting on Raspberry Pi 3B+ even though it worked fine with Raspberry Pi 3B. The new image should work with RPi 3B+ as well.
