### ISSUE TITLE
client fails to start until runtime has been up for 5 minutes

### ISSUE THREAD

**Issue by thomaslea** [angelcam/arrow-client#4]
I have done limited testing on this, but when I build this client into my embedded device it does not successfully start until the system has been running for about 5 minutes.  The failure is here:

/mnt/ramdisk/root # /opt/angelcam/arrow-client arr-rs.angelcam.com:8900 -c /opt/angelcam/ca.pem -r "rtsp://127.0.0.1:554/img/media.sav" --log-stderr -v
2016-03-31 13:15:53 INFO    [src/main.rs:1001] application started (uuid: [removed], mac: [removed])
thread '<main>' panicked at 'arithmetic operation overflowed', src/main.rs:673
note: Run with `RUST_BACKTRACE=1` for a backtrace.

which points to this:

```
        last_scan:         now - NETWORK_SCAN_PERIOD
```

Since NETWORK_SCAN_PERIOD is 300000, this is suspicious....  My device has its local clock set correctly before I attempt to start the client.

**Comment by operutka** [comment]
What a funny bug! Several conditions must be satisfied in order to invoke this panic:
1. non-overflowing arithmetic operations (this is the default behavior in Rust)
2. overflow/underflow checks added by compiler (enabled only in debug setups)
3. the system's high precision clock starts counting from 0 (or less than the `NETWORK_SCAN_PERIOD`)

The `NETWORK_SCAN_PERIOD` equals to 5 minutes and your system's high precision clock seems to start counting from 0. That's why you cannot start the client for the first 5 minutes.

A quick fix for you would be recompiling it with the `--release` option. I'll release a proper fix later today.
