### ISSUE TITLE
Is Raspberry Pi zero supported?

### ISSUE THREAD

**Issue by budnail** [angelcam/arrow-client#43]
I see that Rasperberry Pi 2/3/4 and Orange Pi Zero are listed, no specific call out like "Don't try a Rpi Zero".  Unfortunately that's all I can get my hands on for the moment.

**Comment by operutka** [comment]
Hi @budnail. Sorry for the delay. You can try it and see for yourself if it works. The Arrow Client should work without any issues on RPi Zero.

Personally, I'd avoid using this device because it needs to be connected using WiFi. Depending on the number of IP cameras in your network and their bitrate, it can add quite significant amount of traffic. For example, if you have 4 cameras with 2 Mbps stream each, the device will need handle 8 Mbps down and 8 Mbps up. That's additional 16 Mbps of traffic in your wireless network. The more cameras you have and the higher their bitrate the bigger problem it'll be. And if you're in an area with high number of WiFi networks, it'll be even a bigger issue.

**Comment by budnail** [comment]
Thanks for the info.  I didn’t realize that the camera data actually traveled through the device.  I thought its purpose was only facilitate a direct connection like a dynamic dns client.

I’d rather use Rpi 3 and 4’s for everything I do, but they are so hard to get.  I happened to have several zero's lying around.  I may try it on a two to three camera installation.

**Comment by operutka** [comment]
Yes, the data travel through the device because the device creates an encrypted tunnel to Angelcam Cloud. Otherwise, the video would travel unencrypted. I'm closing the issue but feel free to ask any other questions.

**Comment by budnail** [comment]
Thank you very much.
