### ISSUE TITLE
Orange Pi Zero 2 incompatible?

### ISSUE THREAD

**Issue by westernstatesflooring** [angelcam/arrow-client#47]
I've tried the latest opi release of your angelbox image and the LEDs on the board do not light and it does not boot.  Can you confirm if your Orange Pi image is compatible with the Zero 2?  thank you

**Comment by operutka** [comment]
Hello @westernstatesflooring.

The Orange Pi image was for the original Orange Pi Zero. It won't work with the newer OPi Zero 2. In any case, we've dropped support for Orange Pi because of stability issues. We no longer release or maintain images for these devices.

But don't worry, you can still use your device as AngelBox. You can install our Arrow Client from the APT repository. See the following guide: https://github.com/angelcam/arrow-client/wiki/Turning-your-ARM-device-into-AngelBox#installation-from-our-apt-repository

**Comment by westernstatesflooring** [comment]
Thank you for the update, I'd offer a suggestion you update your documentation that you no longer support the Orange Pi.  I've tried the APT repo route with Debian on the OPi, it wouldn't find any of my cameras however your branded Angelbox that we currently use is finding everything just fine.  So there's something missing with my Arrow Client setup.

**Comment by westernstatesflooring** [comment]
More info.  Here's the error I get in Angelcam.  I've followed the instructions exactly.

![image](https://user-images.githubusercontent.com/47370106/193630668-68164ee4-db6c-4cf9-b9b5-87789ca2970d.png)


`sudo apt-get update
sudo apt-get install dirmngr
sudo apt-key adv --keyserver keys.openpgp.org --recv-keys 382B7B1C7F1838240D9DF4E1A244DAA87FBFBC65
sudo sh -c 'echo "deb http://apt.angelcam.com/raspbian-stretch stable main" > /etc/apt/sources.list.d/arrow.list'
sudo apt-get update
sudo apt-get install arrow-box
The arrow-box service gets started automatically after installation of the package. If you need to start/stop it manually, you can use standard systemd commands:

sudo systemctl start arrow-box.service
sudo systemctl stop arrow-box.service
All logs go into syslog. If you need to modify the arrow-client startup parameters, you can modify them in the /etc/default/arrow-box file. To list all available parameters, run the following command:

/usr/local/arrow-box/arrow-client`

**Comment by operutka** [comment]
Your setup should be OK. The problem is most likely in the network hardware or (more likely) drivers. We've experienced issues like this with other cheap devices. They often use some obscure network hardware where only poor-quality drivers are available in the Linux kernel and the promiscuous mode, which is required for the network scanning, is either buggy or does not work at all.

You can try using Armbian instead of Debian. It's based on Debian, so the APT package should work. There is a small chance that Armbian will use better drivers as it is a distribution focused on these devices.
