### ISSUE TITLE
Unable add MJPEG stream from mjpeg-streamer

### ISSUE THREAD

**Issue by SingingDwarf** [angelcam/arrow-client#8]
I have MJPEG-Streamer running on one box on my local network, which I can view in a browser using http://192.168.0.104:8080/?action=stream

I have installed arrow-client on a second box from the deb package (NB the certificates failed during installation but I installed these manually using `sudo apt-key adv --keyserver hkp://keyserver.searchy.nl --recv-keys 3CB6723D` and the second key.

I edited /usr/bin/arrow-box to the following:

```
#!/bin/bash

ARROW_BOX_HOME=/usr/local/arrow-box

# Give the DHCP client some time to configure the interface.
sleep 10

# Run the self-diagnostic script if it is present.
if [ -f /usr/local/arrow-box-utils/self-diagnose ]; then
    perl /usr/local/arrow-box-utils/self-diagnose eth0
    # Check if it is safe to continue or halt the system in case it is in 
    # diagnostic environment.
    if [ $? -gt 0 ]; then
        halt
    fi
fi

while true; do
  echo "disconnected" > /var/lib/arrow/state
  $ARROW_BOX_HOME/arrow-client arr-rs.angelcam.com:8900 -d \
    -c $ARROW_BOX_HOME/ca.pem \
    -c /usr/share/ca-certificates \
    -h 192.168.0.104:8080 \
    -i wlan0
  logger "the Arrow Client process has terminated"
  sleep 10
done
```
syslog shows the following when I try to add the camera to my.angelcam.com:

```
Apr 24 12:32:19 raspi-cam systemd[1]: Starting arrow-box...
Apr 24 12:32:19 raspi-cam systemd[1]: Started arrow-box.
Apr 24 12:32:29 raspi-cam arrow-client[2185]: [src/main.rs:1332] application started (uuid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx, mac: xx:xx:xx:xx:xx:xx)
Apr 24 12:32:29 raspi-cam arrow-client[2185]: [src/main.rs:472] connecting to remote Arrow Service arr-rs.angelcam.com:8900
Apr 24 12:32:29 raspi-cam arrow-client[2185]: [src/main.rs:633] looking for local services...
Apr 24 12:32:31 raspi-cam arrow-client[2185]: [src/main.rs:472] connecting to remote Arrow Service m4-eu3.angelcam.com:8901
Apr 24 12:32:59 raspi-cam arrow-client[2185]: [src/main.rs:655] 0 services found, current service table: {"services":[{"svc_type":5,"mac":"xx:xx:xx:xx:xx:xx","address":"192.168.0.104:8080","path":"","static_svc":true,"last_seen":1493033549,"active":true}]}
```

But the stream is not found.

/etc/arrow/mjpeg-paths contains the path /?action=stream so I was expecting this to work OK.

Any ideas please?

**Comment by SingingDwarf** [comment]
Follow-up:

Running `sudo /usr/local/arrow-box/arrow-client arr-rs.angelcam.com:8900 -h 192.168.0.109:8080` I get the following in /var/log/syslog:

`Apr 24 12:49:02 raspi-cam arrow-client[808]: [src/main.rs:1332] application started (uuid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, mac: xx:xx:xx:xx:xx:xx)
Apr 24 12:49:03 raspi-cam arrow-client[808]: [src/main.rs:472] connecting to remote Arrow Service arr-rs.angelcam.com:8900
Apr 24 12:49:03 raspi-cam arrow-client[808]: [src/main.rs:497] OpenSSL error: The OpenSSL library reported an error: certificate verify failed
Apr 24 12:49:03 raspi-cam arrow-client[808]: [src/main.rs:513] retrying in 59.823 seconds
`

So it appears that something went wrong with the certificates.

Running the installation again, the certifications cannot be installed:

`pi@raspi-cam:~ $ sudo apt-get install arrow-box
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libavcodec56 libavformat56 libavresample2 libavutil54 libdrm-amdgpu1 libdrm-nouveau2 libdrm-radeon1 libelf1 libgsm1
  libjpeg8 libllvm3.9 libmp3lame0 libmysqlclient18 libogg0 libopenjpeg5 libopus0 liborc-0.4-0 libschroedinger-1.0-0
  libspeex1 libtheora0 libva1 libvorbis0a libvorbisenc2 libvpx1 libx11-xcb1 libx264-142 libxcb-dri2-0 libxcb-dri3-0
  libxcb-present0 libxcb-sync1 libxshmfence1 libxvidcore4 mesa-va-drivers mysql-common va-driver-all
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  arrow-box
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 0 B/618 kB of archives.
After this operation, 2,126 kB of additional disk space will be used.
Selecting previously unselected package arrow-box.
(Reading database ... 33265 files and directories currently installed.)
Preparing to unpack .../arrow-box_6.1-1_armhf.deb ...
Unpacking arrow-box (6.1-1) ...
Setting up arrow-box (6.1-1) ...
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.4XcDT1VPGR --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keys.gnupg.net --recv-keys 3CB6723D
gpg: requesting key 3CB6723D from hkp server keys.gnupg.net
?: keys.gnupg.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.P5uVCcQuJi --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keys.gnupg.net --recv-keys 6C2D5DE7
gpg: requesting key 6C2D5DE7 from hkp server keys.gnupg.net
?: keys.gnupg.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
dpkg: error processing package arrow-box (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 arrow-box
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

But running those commands with another public key server appears to work OK:

`pi@raspi-cam:~ $ gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.4XcDT1VPGR --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.searchy.nl --recv-keys 3CB6723D
gpg: keyblock resource `/tmp/tmp.4XcDT1VPGR/secring.gpg': file open error
gpg: requesting key 3CB6723D from hkp server keyserver.searchy.nl
gpg: key 3CB6723D: "Ondřej Perutka <ondrej.perutka@angelcam.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
pi@raspi-cam:~ $ gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.4XcDT1VPGR --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.searchy.nl --recv-keys 6C2D5DE7
gpg: keyblock resource `/tmp/tmp.4XcDT1VPGR/secring.gpg': file open error
gpg: requesting key 6C2D5DE7 from hkp server keyserver.searchy.nl
gpg: key 6C2D5DE7: "click2stream, Inc. <info@angelcam.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
`

**Comment by operutka** [comment]
Hi @SingingDwarf,

there is a lot to answer, so let me start from the beginning. The `-r`, `-m` and `-h` parameters have no effect on the network scanner. The scanner is completely independent.

It looks for active hosts in your local networks, then it tries to open a few selected ports on the hosts from the first step, then it tries to guess the protocol for every open port, and then for all HTTP and RTSP services discovered using the previous steps, it checks all the stream paths from the files you mentioned.

If you need to add a service manually for some reason (e.g. because the network scanner was not able to find the service), you can use the `-r`, `-m` and `-h` parameters but these services won't get touched by the network scanner. You need to specify exactly what you want (correct service type and full URL). The `-h` parameter won't work for MJPEG services, it's for "plain" HTTP services (e.g. IP camera web interface). Moreover, standalone HTTP services are not shown in our camera connector at my.angelcam.com. If you need to add an MJPEG service, you need to use the `-m` parameter and specify full URL of the stream.

Long story short - this is probably what you are looking for:

```bash
...

while true; do
  echo "disconnected" > /var/lib/arrow/state
  $ARROW_BOX_HOME/arrow-client arr-rs.angelcam.com:8900 -d \
    -c $ARROW_BOX_HOME/ca.pem \
    -c /usr/share/ca-certificates \
    -m "http://192.168.0.104:8080/?action=stream" \
    -i wlan0
  logger "the Arrow Client process has terminated"
  sleep 10
done
```

Regarding the certificates, there are different sets of certificates. The certificate you install using `sudo apt-key adv ...` and the certificates that are installed in the post-installation script using `gpg ...` are only for APT. They are used only for verifying signatures of packages from our APT repository. The Arrow Client itself does not use these certificates. It uses certificates from `/usr/share/ca-certificates` and the `$ARROW_BOX_HOME/ca.pem` certificate. However, you need to tell the client where to find its certificates using the `-c` parameter. The reason why you saw the OpenSSL error in your syslog was that you did not use the `-c` parameter.

The problem with installing the APT key/certificate from hkp://keys.gnupg.net is a different story. The server might just have been unavailable at the time you tried it or it's no longer available. I'll try to find out what happened and update the documentation if needed.

**Comment by SingingDwarf** [comment]
Thank you - I have now progressed much further. Thank you for the assistance and for clarifying matters with regards to the certificates.

**Comment by operutka** [comment]
You're welcome. Let me know if you have any further questions.
